var quotes = [
'I be getting high just to balance out the lows.- Drake',
'Music is like a dream. One that I cannot hear. Beethoven',
'Without music, life would be a mistake. Nietzsche',
'Music can change the world. Ludwig van Beethoven ',
	'Close your eyes. Listen. Nothings missing. Maxime Lagacé ',
	'Music is the universal language of mankind. Henry Wadsworth Longfellow ',
	'My music fights against the system that teaches to live and die. Bob Marley ',
	'A bird does not sing because it has an answer. It sings because it has a song. Chinese proverb ',
	'Music is nothing else but wild sounds civilized into time and tune. Thomas Fuller ',
	'Life seems to go on without effort when I am filled with music. George Eliot ',
	'Music gives a soul to the universe, wings to the mind, flight to the imagination and life to everything. Plato ',
	'Music expresses that which cannot be said and on which it is impossible to be silent. Victor Hugo ',
	'Music touches us emotionally, where words alone can\'t. Johnny Depp ',
	'Music is an outburst of the soul. Frederick Delius ',
	'If music be the food of love, play on. William Shakespeare',
	'Music is the art which is most nigh to tears and memory. Oscar Wilde',
	'After silence, that which comes nearest to expressing the inexpressible is music. Aldous Huxley',
	'And those who were seen dancing were thought to be insane by those who could not hear the music. Friedrich Nietzsche',
	'If I cannot fly, let me sing. Stephen Sondheim',
	'Where words fail, music speaks. Hans Christian Andersen',
	'You are the music while the music lasts. T.S. Eliot',
	'Music comes from a place we don\'t know. Chris Martin (Coldplay)',
	'Music is what tell us that the human race is greater than we realize. Napoleon Bonaparte ',
	'Music is well said to be the speech of angels. Thomas Carlyle ',
	'If Music is a Place — then Jazz is the City, Folk is the Wilderness, Rock is the Road, Classical is a Temple. Vera Nazarian',
	'Music, once admitted to the soul, becomes a sort of spirit, and never dies. Edward Bulwer-Lytton',
	'A great song should lift your heart, warm the soul and make you feel good. Colbie Caillat',
	'Life is a song. Love is the music. (Submitted by the Wisdom Quotes Community) ',
	'Music is the art of the prophets and the gift of God. Martin Luther',
	'Music is the wine that fills the cup of silence. Robert Fripp',
	'My job has very little to do with music. It has more to do with taste and culture and balance. Rick Rubin',
	'Music and silence combine strongly because music is done with silence, and silence is full of music. Marcel Marceau',
	'Music, when soft voices die, vibrates in the memory. Percy Bysshe Shelley',
	'No matter how corrupt, greedy, and heartless our government, our corporations, our media, and our religious and charitable institutions may become, the music will still be wonderful. Kurt Vonnegut',
	'When I hear music, I fear no danger. I am invulnerable. I see no foe. I am related to the earliest times, and to the latest. Henry David Thoreau',
	'Who hears music feels his solitude peopled at once. Robert Browning',
	'Ive found that no matter what life throws at me, music softens the blow. Bryce Anderson',
	'Music can name the unnameable and communicate the unknowable. Leonard Bernstein',
	'Music has a poetry of its own, and that poetry is called melody. Joshua Logan',
	'Music in the soul can be heard by the universe. Lao Tzu (This is one of my favorite music quote. ',
	'I don\'t make music for eyes. I make music for ears. Adele ',
	'Music is my religion. Jimi Hendrix',
	'Jazz is not just music, its a way of life, its a way of being, a way of thinking. Nina Simone',
	'Music is a higher revelation than all wisdom &amp; philosophy. Ludwig van Beethoven',
	'Music is like a dream. One that I cannot hear. Ludwig van Beethoven',
	'Music should strike fire from the heart of man, and bring tears from the eyes of woman. ',
	'Music is the mediator between the spiritual and the sensual life. Ludwig van Beethoven',
	'The music is not in the notes, but in the silence between. Wolfgang Amadeus Mozart',
	'Music is an agreeable harmony for the honor of God and the permissible delights of the soul. Johann Sebastian Bach',
	'Bach is an astronomer, discovering the most marvellous stars. Beethoven challenges the universe. I only try to express the soul and the heart of man. Frédéric Chopin',
	'Information is not knowledge. Knowledge is not wisdom. Wisdom is not truth. Truth is not beauty. Beauty is not love. Love is not music. Music is the best. Frank Zappa',
	'To live is to be musical, starting with the blood dancing in your veins. Everything living has a rhythm. Do you feel your music? Michael Jackson',
	'People ask me how I make music. I tell them I just step into it. It\'s like stepping into a river and joining the flow. Every moment in the river has its song. Michael Jackson',
	'One good thing about music, when it hits you, you feel no pain. Bob Marley',
	'Music is the emotional life of most people. Leonard Cohen',
	'If you have to ask what jazz is, youll never know. Louis Armstrong ',
	'Music is a great natural high and a great natural escape. Shania Twain',
	'I merely took the energy it takes to pout and wrote some blues. Duke Ellington',
	'I wanted to prove the sustaining power of music. David Bowie',
	'Music is powerful. As people listen to it, they can be affected. They respond. Ray Charles',
	'If I were not a physicist, I would probably be a musician. I often think in music. I live my daydreams in music. I see my life in terms of music. ',
	'My music will go on forever. Maybe it\'s a fool say that, but when me know facts me can say facts. My music will go on forever. Bob Marley',
	'Sometimes I feel like rap music is almost the key to stopping racism. Eminem',
	'The world\'s most famous and popular language is music. Psy',
	'I see my life in terms of music. Albert Einstein ',
	'He who sings frightens away his ills. Miguel de Cervantes',
	'Hell is full of musical amateurs. George Bernard Shaw',
	'Music, my rampart and my only one. Edna St. Vincent Millay',
	'Some people have lives; some people have music. John Green',
	'It is always fatal to have music or poetry interrupted. George Eliot',
	'Philosophy is the highest music. Plato',
	'Music is the shorthand of emotion. Leo Tolstoy',
	'Music  what a powerful instrument, what a mighty weapon! Maria Augusta von Trapp',
	'The pause is as important as the note. Truman Fisher',
	'Music is the poetry of the air. Richter',
	'Music is the strongest form of magic. Marilyn Manson',
	'Music is the color of sound. Unknown',
	'Music should be your escape. Missy Elliott',
	'You can cage the singer but not the song. Harry Belafonte',
	'Without music, life would be a mistake. Friedrich Nietzsche ',
	'Music is what life sounds like. Eric Olson',
	'Every life has a soundtrack. Jodi Picoult',
	'I think that music has an endless life. Anne Dudley',
	'Where words leave off, music begins. Heinrich Heine',
	'Music is like a huge release of tension. James Taylor',
	'When words fail music speaks. Irena Huang',
	'Music is my higher power. Oliver James',
	'I haven\'t understood a bar of music in my life, but I have felt it. Igor Stravinsky ',
	'The best music is essentially there to provide you something to face the world with. Bruce Springsteen',
	'It\'s pretty cool to see how far music can take you. Luke Bryan',
	'Music hits us in a really emotional way. For me, it took me away in a way that nothing else could. Rick Rubin',
	'If, while at the piano, you attempt to form little melodies, that is very well; but if they come into your mind of themselves, when you are not practicing, you may be still more pleased; for the internal organ of music is then roused in you. The fingers must do what the head desires; not the contrary. Robert Schumann',
	'Music is a language that doesn\'t speak in particular words. It speaks in emotions, and if it\'s in the bones, it\'s in the bones. Keith Richards',
	'We grown-up people think that we appreciate music, but if we realized the sense that an infant has brought with it of appreciating sound and rhythm, we would never boast of knowing music. The infant is music itself. Hazrat Inayat Khan',
	'I love the relationship that anyone has with music because there\'s something in us that is beyond the reach of words, something that eludes and defies our best attempts to spit it out. It\'s the best part of us probably. Nick Hornby',
	'Live your truth. Express your love. Share your enthusiasm. Take action towards your dreams. Walk your talk. Dance and sing to your music. Embrace your blessings. Make today worth remembering. Steve Maraboli',
	'I need music. It\'s like my heartbeat, so to speak. It keeps me going no matter what\'s going on – bad games, press, whatever! LeBron James',
	'My idea is that there is music in the air, music all around us; the world is full of it, and you simply take as much as you require. Edward Elgar',
	'Music drives you. It wakes you up, it gets you pumping. And, at the end of the day, the correct tune will chill you down. Dimebag Darrell',
	'You have to, take a deep breath. and allow the music to flow through you. Revel in it, allow yourself to awe. When you play allow the music to break your heart with its beauty. Kelly White',
	'Music is your own experience, your thoughts, your wisdom. If you dont live it, it wont come out of your horn. Charlie Parker',
	'A painter paints pictures on canvas. But musicians paint their pictures on silence. Leopold Stokowski',
	'That\'s why people listen to music or look at paintings. To get in touch with that wholeness. Corita Kent',
	'Music is a safe kind of high. Jimi Hendrix ',
	'Play it fuckin loud! Bob Dylan',
	'A gentleman is someone who knows how to play the banjo and doesnt. Mark Twain',
	'Do you know people who insist they like ‘all kinds of music\'. That actually means they like no kinds of music. Chuck Klosterman',
	'Music is much like fucking, but some composers cant climax and others climax too often, leaving themselves and the listener jaded and spent. Charles Bukowski',
	'I love the way music inside a car makes you feel invisible; if you play the stereo at max volume, it\'s almost like the other people can\'t see into your vehicle. It tints your windows, somehow. Chuck Klosterman',
	'Without music to decorate it, time is just a bunch of boring production deadlines or dates by which bills must be paid. Frank Zappa',
	'Music is everybody\'s business. It\'s only the publishers who think people own it. ',
	'I\'m just a musical prostitute, my dear. Freddie Mercury',
	'There are two means of refuge from the miseries of life: music and cats. Albert Schweitzer',
	'If one plays good music, people dont listen, and if one plays bad music people dont talk. Oscar Wilde',
	'Music makes one feel so romantic – at least it always gets on one\'s nerves – which is the same thing nowadays. Oscar Wilde',
	'Ive always thought people would find a lot more pleasure in their routines if they burst into song at significant moments. John Barrowman',
	'Jazz will endure just as long as people hear it through their feet instead of their brains. John Philip Sousa',
	'Even if you cant sing well, sing. Sing to yourself. Sing in the privacy of your home. But sing. Rebbe Nachman of Breslov',
	'All the good music has already been written by people with wigs and stuff. Frank Zappa',
	'Writing about music is like dancing about architecture. Frank Zappa',
	'Jazz isnt dead. It just smells funny. Frank Zappa ',
	'That\'s the amazing thing about music: there\'s a song for every emotion. Can you imagine a world with no music? It would suck. Harry Styles',
	'I would rather write 10,000 notes than a single letter of the alphabet. Ludwig van Beethoven',
	'Country music is three chords and the truth. Harlan Howard',
	'Good music is good music, and everything else can go to hell. Dave Matthews',
	'I like beautiful melodies telling me terrible things. Tom Waits',
	'The only truth is music. Jack Kerouac ',
	'Everything in the universe has a rhythm, everything dances. ',
	'Melody is, and ever will be, the very flower of music. August W. Ambros',
	'In music the passions enjoy themselves. Friedrich Nietzsche',
	'The man that hath no music in himself, nor is not moved with concord of sweet sounds, is fit for treasons, stratagems, and spoils; the motions of his spirit are dull as night, and his affections dark as Erebus. Let no such man be trusted. Mark the music. William Shakespeare',
	'Melody is the essence of music. I compare a good melodist to a fine racer, and counterpointists to hack post-horses; therefore be advised, let well alone and remember the old Italian proverb: Chi sa più, meno sa – Who knows most, knows least. Wolfgang Amadeus Mozart',
	'Words make you think. Music makes you feel. A song makes you feel a thought. E.Y. Harburg',
	'Music is the moonlight in the gloomy night of life. Jean Paul Friedrich Richter',
	'We are the music makers, and we are the dreamers of dreams. Arthur O\'Shaughnessy',
	'Our sweetest songs are those that tell of saddest thought. Percy Bysshe Shelley',
	'Poetry, plays, novels, music, they are the cry of the human spirit trying to understand itself and make sense of our world. L.M. Elliott',
	'The times you lived through, the people you shared those times with  nothing brings it all to life like an old mix tape. It does a better job of storing up memories than actual brain tissue can do. Every mix tape tells a story. Put them together, and they can add up to the story of a life. Rob Sheffield',
	'Music is the one incorporeal entrance into the higher world of knowledge which comprehends mankind but which mankind cannot comprehend. Ludwig van Beethoven',
	'Life, he realized, was much like a song. In the beginning there is mystery, in the end, there is confirmation, but it\'s in the middle where all the emotion resides to make the whole thing worthwhile. Nicholas Sparks',
	'All deep things are song. It seems somehow the very central essence of us, song; as if all the rest were but wrappages and hulls! Thomas Carlyle',
	'Songs wont save the planet, but neither will books or speeches. Pete Seeger',
	'There is nothing stable in the world; uproars your only music. John Keats',
	'To hell with reality! I want to die in music, not in reason or in prose. Louis-Ferdinand Céline',
	'Music brings a warm glow to my vision, thawing mind and muscle from their endless wintering. Haruki Murakami',
	'Music is the literature of the heart; it commences where speech ends. Alphonse de Lamartine',
	'Music could ache and hurt, that beautiful music was a place a suffering man could hide. Pat Conroy',
	'Music is the language of the spirit. It opens the secret of life bringing peace, abolishing strife. Kahlil Gibran',
	'Music is the divine way to tell beautiful, poetic things to the heart. Pablo Casals',
	'I tell you such fine music waits in the shadows of hell. Charles Bukowski',
	'Songs are as sad as the listener. Jonathan Safran Foer',
	'Most people die with their music still locked up inside them. Benjamin Disraeli',
	'Music produces a kind of pleasure which human nature cannot do without. Confucius ',
	'A song will outlive all sermons in the memory. Henry Giles',
	'Music is the only thing I\'ve ever known that doesn\'t have any rules at all. Josh Homme',
	'Music is enough for a lifetime, but a lifetime is not enough for music. Sergei Rachmaninoff',
	'I think there is a song out there to describe just about any situation. Criss Jami',
	'Beethoven tells you what it\'s like to be Beethoven and Mozart tells you what it\'s like to be human. Bach tells you what it\'s like to be the universe. Douglas Adams',
	'Music cleanses the understanding; inspires it, and lifts it into a realm which it would not reach if it were left to itself. Henry Ward Beecher',
	'Music. A meaningless acceleration in the rhythm of celestial experience. C.S. Lewis',
	'Pop music often tells you everything is OK, while rock music tells you that its not OK, but you can change it. Bono',
	'Musical innovation is full of danger to the State, for when modes of music change, the fundamental laws of the State always change with them. Plato',
	'How is it that music can, without words, evoke our laughter, our fears, our highest aspirations? Jane Swan',
	'The most exciting rhythms seem unexpected and complex, the most beautiful melodies simple and inevitable. W.H. Auden',
	'Most of what we take as being important is not material, whether its music or feelings or love. Theyre things we cant really see or touch. Theyre not material, but theyre vitally important to us. Judy Collins',
	'Music expresses feeling and thought, without language; it was below and before speech, and it is above and beyond all words. Robert G. Ingersoll',
	'There is no such thing as happy music. Franz Schubert',
	'Songs are sneaky things; they can slip across borders. Pete Seeger',
	'Music is feeling. You can try to verbalize it. It really just hits you or it doesn\'t. Gene Simmons',
	'Tell me what you listen to, and I\'ll tell you who you are. Tiffanie DeBartolo',
	'The market didn\'t define the music; the music defined the market. Charlie Hunter',
	'A strange art – music – the most poetic and precise of all the arts, vague as a dream and precise as algebra. Guy de Maupassant',
	'Music is the only language in which you cannot say a mean or sarcastic thing. John Erskine',
	'Music is good to the melancholy, bad to those who mourn, and neither good nor bad to the deaf. Baruch Spinoza',
	'Music with dinner is an insult both to the cook and the violinist. G.K. Chesterton',
	'Music is to the soul what words are to the mind. Modest Mouse',
	'Without music, life would be a blank to me. Jane Austen ',
	'Wake up, live your life and sing the melody of your soul. Amit Ray',
	'Were it not for music, we might in these days say, the beautiful is dead. Benjamin Disraeli',
	'Life is like a beautiful melody, only the lyrics are messed up. Hans Christian Andersen',
	'Music produces a kind of pleasure which human nature cannot do without. Confucius',
	'Life is for the living. Death is for the dead. Let life be like music. And death a note unsaid. Langston Hughes',
	'Music isn\'t just a pleasure, a transient satisfaction. It\'s a need, a deep hunger; and when the music is right, it\'s joy. Love. A foretaste of heaven. Orson Scott Card',
	'The easiest way to avoid wrong notes is to never open your mouth and sing. What a mistake that would be. Pete Seeger',
	'You must always believe that life is as extraordinary as music says it is. Rebecca West',
	'Music, once admitted to the soul, becomes a sort of spirit, and never dies. Edward George Bulwer-Lytton',
	'Life is one grand sweet song so start the music. Ronald Reagan',
	'Some days there wont be a song in your heart. Sing anyway. Emory Austin',
	'Music is the tool to express life – and all that makes a difference. Herbie Hancock',
	'Without music, life is a journey through a desert. Pat Conroy',
	'As long as we live, there is never enough singing. Martin Luther ',
	'Music is a weapon in the war against unhappiness. Jason Mraz',
	'We should consider every day lost on which we have not danced at least once. Friedrich Nietzsche',
	'Excuse me if I have some place in my mind where I go time to time. Tom Petty',
	'Music is a friend of labor for it lightens the task by refreshing the nerves and spirit of the worker. William Green',
	'A fine work of art  music, dance, painting, story  has the power to silence the chatter in the mind and lift us to another place. Robert McKee',
	'Joy, sorrow, tears, lamentation, laughter – to all these music gives voice, but in such a way that we are transported from the world of unrest to a world of peace, and see reality in a new way, as if we were sitting by a mountain lake and contemplating hills and woods and clouds in the tranquil and fathomless water. Albert Schweitzer',
	'Music will help dissolve your perplexities and purify your character and sensibilities, and in time of care and sorrow, will keep a fountain of joy alive in you. Dietrich Bonhoeffer',
	'It is incontestable that music induces in us a sense of the infinite and the contemplation of the invisible. Victor de LaPrade',
	'I dont sing because Im happy; Im happy because I sing. William James ',
	'The music enchanted the air. It was like the south wind, like a warm night, like swelling sails beneath the stars, completely and utterly unreal It made everything spacious and colourful, the dark stream of life seemed pulsing in it; there were no burdens any more, no limits. Erich Maria Remarque',
	'Work which one hopes may be of some use; then rest, nature, books, music, love for ones neighbor — such is my idea of happiness. Leo Tolstoy',
	'Music fills the present with electric ecstasy. James Lendall Basford',
	'Those who wish to sing always find a song. Unknown',
	'Music is love in search of a word. Sidney Lanier ',
	'The more you love music, the more music you love. Tom Moon',
	'There is no truer truth obtainable by man than comes of music. Robert Browning',
	'If it werent for music, I would think that love is mortal. Mark Helprin',
	'Music is love, love is music, music is life, and I love my life. A. J. McLean',
	'If you were music, I would listen to you ceaselessly, and my low spirits would brighten up. Anna Akhmatova',
	'Magic exists. Who can doubt it, when there are rainbows and wildflowers, the music of the wind and the silence of the stars. Anyone who has loved has been touched by magic. It is such a simple and such an extraordinary part of the lives we live. Nora Roberts',
	'If you\'ve lost your faith in love and music then the end won\'t be long. Pete Doherty',
	'If I should ever die, God forbid, let this be my epitaph: The only proof he needed for the existence of god was music. Kurt Vonnegut',
	'Music is a talent given to me by God. A medium and a platform and a way to spread a message of righteousness… a message of love, a message of unity. Stephen Marley',
	'To stop the flow of music would be like the stopping of time itself, incredible and inconceivable. Aaron Copland',
	'Everything in me feels fluttering and free, like I could take off from the ground at any second. Music, I think, he makes me feel like music. Lauren Oliver',
	'If you were music, I would listen to you ceaselessly, and my low spirits would brighten up. Anna Akhmatova',
	'If it weren\'t for music, I would think that love is mortal. Mark Helprin',
	'Music has been my playmate, my lover, and my crying towel. Buffy Sainte-Marie',
	'Love is friendship set to music. Jackson Pollock',
	'Music, my rampart and my only one. Edna St. Vincent Millay',
	'Chamber music  a conversation between friends. Catherine Drinker Bowen ',
	'Music is a way to dream together and go to another dimension. Cecilia Bartoli',
	'You create a community with music, not just at concerts but by talking about it with your friends. David Byrne',
	'The true beauty of music is that it connects people. It carries a message, and we, the musicians, are the messengers. Roy Ayers',
	'Are we not formed, as notes of music are, for one another, though dissimilar? Percy Bysshe Shelley',
	'Music is very spiritual, it has the power to bring people together. Edgar Winter',
	'He not busy being born is busy dying. Bob Dylan ',
	'To play without passion is inexcusable! Ludwig von Beethoven.',
	'When you play, never mind who listens to you. Robert Schumann',
	'A lot of music is mathematics. It\'s balance. Mel Brooks',
	'When you can write music that endures, bravo. Until then, keep quiet and study the work of those who can. Jennifer Donnelly',
	'Im not saying Im gonna change the world, but I guarantee that I will spark the brain that will change the world. Tupac Shakur',
	'I used to think anyone doing anything weird was weird. Now I know that it is the people that call others weird that are weird. Paul McCartney',
	'If being an egomaniac means I believe in what I do and in my art or music, then in that respect you can call me that I believe in what I do, and Ill say it. John Lennon',
	'If a composer could say what he had to say in words he would not bother trying to say it in music. Gustav Mahler',
	'I play until my fingers are blue and stiff from the cold, and then I keep on playing. Until I\'m lost in the music. Until I am the music – notes and chords, the melody and harmony. It hurts, but it\'s okay because when I\'m the music, I\'m not me. Not sad. Not afraid. Not desperate. Not guilty. Jennifer Donnelly',
	'Music sounds different to the one who plays it. It is the musician\'s curse. Patrick Rothfuss',
	'It\'s never too late to do anything new when it comes to music. Sivamani',
	'Silence is the fabric upon which the notes are woven. Lawrence Duncan',
	'When you make music or write or create, it\'s really your job to have mind-blowing, irresponsible, condomless sex with whatever idea it is you\'re writing about at the time. Lady Gaga',
	'Color directly influences the soul. Color is the keyboard, the eyes are the hammers, the soul is the piano with many strings. The artist is the hand that plays, touching one key or another purposively, to cause vibrations in the soul. Wassily Kandinsky',
	'It is dreadful when something weighs on your mind, not to have a soul to unburden yourself to. You know what I mean. I tell my piano the things I used to tell you. Frédéric Chopin',
	'I am focused on the work. I am constantly creating. I am a busy girl. I live and breathe my work. I love what I do. I believe in the message. Theres no stopping. I didnt create the fame, the fame created me. Lady Gaga',
	'There are not more than five musical notes, yet the combinations of these five give rise to more melodies than can ever be heard. Sun Tzu',
	'I dont think you get to good writing unless you expose yourself and your feelings. Deep songs dont come from the surface; they come from the deep down. The poetry and the songs that you are suppose to write, I believe are in your heart. Judy Collins',
	'Music is something that should speak for itself, straight from the heart. It took me a long time to understand that. Damon Albarn',
	'This will be our reply to violence: to make music more intensely, more beautifully, more devotedly than ever before. Leonard Bernstein',
	'There is nothing more to be said or to be done tonight, so hand me over my violin and let us try to forget for half an hour the miserable weather and the still more miserable ways of our fellowmen. Arthur Conan Doyle',
	'It was his nature to blossom into song, as it is a trees to leaf itself in April. Alexander Smith',
	'Improvised music involves a lot of intuition and I like developing intuition. Fred Frith',
	'Music is a liberal science, and ought to be liberally upheld. Olivia Dussek Buckley',
	'A poets mission is to make words do more work than they normally do, to make them work on more than one level. Jay-Z',
	'To me, the greatest pleasure of writing is not what it\'s about, but the music the words make. Truman Capote',
	'Music is a whole oasis in my head. The creation process is so personal and fulfilling. River Phoenix',
	'Any good music must be an innovation. Les Baxter ',
	'Music washes away from the soul the dust of everyday life. Berthold Auerbach ',
	'Musics the medicine of the mind. John A. Logan',
	'Music was my refuge. I could crawl into the space between the notes and curl my back to loneliness. Maya Angelou',
	'It was the moment I realized what music can do to people, how it can make you hurt and feel so good all at once. Nina LaCour',
	'The music we listen to may not define who we are. But it\'s a good start. Jodi Picoult',
	'Softly, deftly, music shall caress you. Hear it, feel it, secretly possess you. Charles Hart',
	'Take a music bath once or twice a week for a few seasons. You will find it is to the soul what a water bath is to the body. Oliver Wendell Holmes',
	'Music acts like a magic key, to which the most tightly closed heart opens. Maria Augusta von Trapp',
	'People haven\'t always been there for me but music always has. Taylor Swift',
	'I think ',
	'He took his pain and turned it into something beautiful. Into something that people connect to. And that\'s what good music does. It speaks to you. It changes you. Hannah Harrington',
	'Music enriches people\'s lives in the same way paintings and literature do. Everybody deserves that. Victoria Wood',
	'Music became a healer for me. And I learned to listen with all my being. I found that it could wipe away all the emotions of fear and confusion relating to my family. Eric Clapton',
	'Music is the great uniter. An incredible force. Something that people who differ on everything and anything else can have in common. Sarah Dessen',
	'A man should hear a little music [] in order that worldly cares may not obliterate the sense of the beautiful which God has implanted in the human soul. Johann Wolfgang von Goethe',
	'If I had my life to live over again, I would have made a rule to read some poetry and listen to some music at least once every week. Charles Darwin',
	'I\'m wishing he could see that music lives. Forever. That it\'s stronger than death. Stronger than time. And that its strength holds you together when nothing else can. Jennifer Donnelly',
	'For me, there is ',
	'No matter who we are, no matter what our circumstances, our feelings and emotions are universal. And music has always been a great way to make people aware of that connection. It can help you open up a part of yourself and express feelings you didn\'t know you were feeling. Josh Groban',
	'Music is therapy. Music moves people. It connects people in ways that no other medium can. It pulls heart strings. It acts as medicine. Macklemore',
	'My heart, which is so full to overflowing, has often been solaced and refreshed by music when sick and weary. Martin Luther',
	'I believe 100 percent in the power and importance of music. James Taylor',
	'Music can change the world because it can change people. Bono ',
	'I can not imagine my life if I didnt have a music program in my school. Beyonce',
	'The future belongs to young people with an education and the imagination to create. Barack Obama',
	'I dont think I would have become President if it were not for my school music program. Bill Clinton',
	'Music education can help spark a childs imagination or ignite a lifetime of passion. Hillary Clinton',
	'If I had not studied music, there would be no Macintosh computers today. Jef Raskin',
	'Music is the movement of sound to reach the soul for the education of its virtue. Plato',
	'Music – that\'s been my education. There\'s not a day that goes by that I take it for granted. Billie Joe Armstrong',
	'Music is an element that should be part and parcel of every child\'s life via the education system. Victoria Wood',
	'Music is intended and designed for sentient beings that have hopes and purposes and emotions. Jacques Barzun',
	'Musical training is a more potent instrument than any other, because rhythm and harmony find their way into the inward places of the soul. Plato',
	'I\'ve always said music should make you laugh, make you cry or make you think. Kenny Rogers',
	'For me, everything definitely comes from music. Mike Myers',
	'I have a greater goal  to empower young people through music education. Ruben Studdard',
	'Early music training seems to shape the young brain, strengthening the neural connections and perhaps establishing new ones. Dr. Frances Rauscher',
	'Music enhances the education of our children by helping them to make connections and broadening the depth with which they think and feel. Yo-Yo Ma',
	'If we are to hope for a society of culturally literate people, music must be a vital part of our childrens education. Yo-Yo Ma',
	'Education isnt just about feeding the brain. Art and music feed the heart and soul. Julie Garwood',
	'Music education stimulates, challenges, and enriches our young people during their formative, school years; its value lasts a lifetime. Tammy Baldwin',
	'Music is about communication, creativity, and cooperation, and by studying music in schools, students have the opportunity to build on these skills, enrich their lives, and experience the world from a new perspective. William J. Clinton',
	'If children hear fine music from the day of their birth and learn to play it, they develop sensitivity, discipline and endurance. They get a beautiful heart. Shinichi Suzuki',
	'Music education opens doors that help children pass from school into the world around them  a world of work, culture, intellectual activity, and human involvement. Gerald R. Ford',
	'The future of our nation depends on providing our children with a complete education that includes music. Gerald R. Ford',
	'Whoever has skill in music is of good temperament and fitted for all things. We must teach music in schools. Martin Luther',
	'Music deserves to be the mandatory second language of all schools in the world. Paul Carvel ',
	'Music kept me off the streets and out of trouble and gave me something that was mine that no one could take away from me. Eddie Van Halen',
	'If I can help a kid discover a liking, or even a passion for music in their life, then thats a wonderful thing. Eddie Van Halen',
	'The first step  especially for young people with energy and drive and talent, but not money  the first step to controlling your world is to control your culture. To model and demonstrate the kind of world you demand to live in. ',
	'Music is stored in our long-term memory. When we learn something through music, we tend to remember it longer and believe it more deeply. Joyce Brothers',
	'Music has a power of forming the character, and should therefore be introduced into the education of the young. Aristotle',
	'Our youth should also be educated with music and physical education. Aristotle',
	'Music is a more potent instrument than any other for education. Plato'
]

function newMOTD() {
	var randomNumber = Math.floor(Math.random() * (quotes.length));
	document.getElementById('motdDisplay').innerHTML = quotes[randomNumber];
}
